// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Odin.DataAccess.Context;

namespace Odin.DataAccess.Migrations
{
    [DbContext(typeof(OdinDbContext))]
    partial class OdinDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Odin.Data.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TCIdentityNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alibekir.pasaran@nomail.com",
                            FirstName = "Ali",
                            IsDeleted = false,
                            LastName = "Pasaran",
                            Phone = "05445467893",
                            TCIdentityNumber = "17459647263"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bekir.terzi@nomail.com",
                            FirstName = "Bekir",
                            IsDeleted = false,
                            LastName = "Terzi",
                            Phone = "05558254793",
                            TCIdentityNumber = "83219547632"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mucella.yapici@nomail.com",
                            FirstName = "Mücella",
                            IsDeleted = false,
                            LastName = "Yapıcı",
                            Phone = "05042561782",
                            TCIdentityNumber = "42356178469"
                        },
                        new
                        {
                            Id = 4,
                            Email = "viktor.pasaran@nomail.com",
                            FirstName = "Viktor",
                            IsDeleted = false,
                            LastName = "Panteleev",
                            Phone = "05434587965",
                            TCIdentityNumber = "92473156214"
                        },
                        new
                        {
                            Id = 5,
                            Email = "jasar.ahmedovski@nomail.com",
                            FirstName = "Jasar",
                            IsDeleted = false,
                            LastName = "Ahmedovski",
                            Phone = "05321478214",
                            TCIdentityNumber = "96573145217"
                        });
                });

            modelBuilder.Entity("Odin.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Apple'ın gözdesi ayran",
                            IsDeleted = false,
                            Name = "IRun",
                            Price = 15m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Yarının Kısa Bir Tarihi",
                            IsDeleted = false,
                            Name = "Homo Deus",
                            Price = 30m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dostoyevski",
                            IsDeleted = false,
                            Name = "Suç ve Ceza",
                            Price = 27.5m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Apple'ın gözdesi ayran",
                            IsDeleted = false,
                            Name = "IRun",
                            Price = 14.5m
                        },
                        new
                        {
                            Id = 5,
                            Description = "G3 Laptop For Gamers",
                            IsDeleted = false,
                            Name = "Dell",
                            Price = 14500m
                        });
                });

            modelBuilder.Entity("Odin.Data.Models.Product", b =>
                {
                    b.HasOne("Odin.Data.Models.Customer", null)
                        .WithMany("Products")
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("Odin.Data.Models.Customer", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
